/* Only owner-approved, public-facing product information belongs here. */
(() => {
 const data={updated:'2026-10-06',title:'Better ManageBac roadmap',publicURL:'https://abiel990310.github.io/better-managebac-roadmap/',feedbackURL:'https://github.com/Abiel990310/better-managebac-roadmap/issues/new?template=idea.yml',feedbackKind:'github',tracks:[
  {id:'appearance',version:'2.8',title:'Make the workspace yours',status:'completed',summary:'Themes, custom palettes, photo and video backgrounds, and readable page controls.',features:['Light and dark themes','Photo and video backgrounds','Personal color palettes'],track:'chrome'},
  {id:'planning',version:'2.9.0',title:'Plan and keep track',status:'completed',summary:'Find upcoming work, save important tasks, edit personal tasks and keep a backup.',features:['Deadline Focus and search','Personal task editing','Backup and restore'],track:'chrome'},
  {id:'grades',version:'2.9.1',title:'Grades on the dashboard',status:'uploaded',summary:'Experimental published-score graphs, saved results, separate Settings and a skippable first-use tour.',features:['Experimental grade graphs','Saved results and optional opening','Settings and guided tour'],track:'chrome'},
  {id:'grade-trail',version:'2.9.2',title:'Follow what changed',status:'working',summary:'Follow unread grade badges to the right class and score. A public roadmap makes the next steps visible.',features:['Themed subject and term menus','Per-class unread grade highlights','Public roadmap and feedback'],track:'chrome'},
  {id:'reminders',version:'Next idea',title:'Pinned-task reminders',status:'exploring',summary:'Optional reminders for unfinished saved tasks, based on verified deadlines. Dates and privacy need testing before this is scheduled.',features:['Reliable deadline matching','Optional, private reminders'],track:'chrome'},
  {id:'submission',version:'Research',title:'Submission-aware hints',status:'exploring',summary:'Investigate whether ManageBac exposes a reliable student submission state. Uploaded files alone will not count as submitted work.',features:['Student submission checks','Clear, optional prompts'],track:'chrome'},
  {id:'safari',version:'Separate track',title:'Safari catch-up',status:'paused',summary:'Chrome comes first. Safari compatibility and its store release continue as a separate track when work resumes.',features:['Chrome feature catch-up','Safari testing and store review'],track:'safari'}
 ],statuses:{completed:{label:'Completed',detail:'Built in earlier Chrome versions. Store availability may vary.'},uploaded:{label:'Store upload',detail:'Package uploaded; public availability has not been confirmed.'},working:{label:'Working on',detail:'Being built and tested. Owner review comes before release.'},exploring:{label:'Exploring',detail:'An approved direction to investigate, with no promised release date.'},paused:{label:'Paused',detail:'Separate work that is not in the current Chrome update.'}}};
 globalThis.MBRoadmapData=data;if(typeof module!=='undefined')module.exports=data;
})();
