(() => {
 const data=globalThis.MBRoadmapData,el=(tag,attrs={},text='')=>{const node=document.createElement(tag);Object.entries(attrs).forEach(([key,value])=>node.setAttribute(key,value));node.textContent=text;return node;};
 if(!data)return;
 const validURL=value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};
 document.querySelector('#updated').textContent='Last updated '+new Date(data.updated+'T00:00:00').toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});
 const status=id=>el('span',{class:'status '+id,title:data.statuses[id].detail},data.statuses[id].label);
 document.querySelector('#legend').replaceChildren(...Object.keys(data.statuses).map(status));
 function card(item){const box=el('article',{class:'release-card'});box.append(el('h3',{},item.title),el('p',{},item.summary));const list=el('ul',{class:'feature-branches','aria-label':'Features'});item.features.forEach(feature=>list.append(el('li',{},feature)));box.append(list);return box;}
 function render(filter){const items=data.tracks.filter(item=>filter==='all'||item.status===filter),timeline=document.querySelector('#timeline'),other=document.querySelector('#separate-track');timeline.replaceChildren();other.replaceChildren();items.filter(item=>item.track==='chrome').forEach(item=>{const node=el('div',{class:'milestone '+item.status,'data-id':item.id}),meta=el('div',{class:'milestone-meta'});meta.append(el('span',{class:'version'},item.version),status(item.status));node.append(meta,card(item));timeline.append(node);});items.filter(item=>item.track!=='chrome').forEach(item=>{const box=card(item);box.prepend(el('span',{class:'version'},'Safari · '+item.version),status(item.status));other.append(box);});other.hidden=!other.children.length;document.querySelector('#empty').hidden=!!items.length;document.querySelector('#filter-status').textContent=items.length+' roadmap items shown.';}
 render('all');document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(other=>other.setAttribute('aria-pressed',String(other===button)));render(button.dataset.filter);});
 const button=document.querySelector('#theme');let dark=matchMedia('(prefers-color-scheme: dark)').matches;
 const theme=()=>{document.documentElement.dataset.theme=dark?'dark':'light';button.textContent=dark?'Light':'Dark';button.setAttribute('aria-label',dark?'Switch to light appearance':'Switch to dark appearance');};theme();button.onclick=()=>{dark=!dark;theme();};
 const feedback=validURL(data.feedbackURL);if(feedback){const link=document.querySelector('#feedback-link');link.href=feedback;link.hidden=false;document.querySelector('#feedback-unavailable').hidden=true;document.querySelector('#feedback-privacy').textContent=data.feedbackKind==='github'?'Requires a GitHub account. Suggestions and your GitHub profile will be public. Keep school, student and grade details out of your post. Suggestions are not added automatically.':'Opens the feedback form. Do not include student names, grades, school account details or private screenshots. The owner reviews suggestions before anything is added here.';}
})();
